[package]
name = "calcit_wasmtime"
version = "0.1.0"
edition = "2018"

[lib]
name = "calcit_wasmtime"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"] # Creates dynamic lib

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cirru_parser = "0.1.12"
cirru_edn = "0.2.8"
wasmtime = "0.30.0"
regex = "1"
lazy_static = "1.4.0"
