on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: calcit-lang/setup-cr@0.0.7
        with:
          bundler: false

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - run: cargo test
      - run: cargo run --example try_api

      - run: cargo build --release

      - run: rm -rfv dylibs && mkdir dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: cr -1
